# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accauntUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='linkAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='projectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('projectCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_portfolio.accauntUser')),
            ],
        ),
        migrations.AddField(
            model_name='linkaddress',
            name='urlProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_portfolio.projectName'),
        ),
    ]
