# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accauntuser',
            name='picture',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='media/images/', verbose_name='Ваше фото'),
        ),
    ]
