# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 21:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('project_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_address', models.CharField(max_length=100, verbose_name='Почта')),
                ('picture', models.FileField(blank=True, null=True, upload_to='media/images/', verbose_name='Загрузка фото')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Компания')),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Названия проекта')),
                ('projectCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_portfolio.MyUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='accauntuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='linkaddress',
            name='urlProject',
        ),
        migrations.RemoveField(
            model_name='projectname',
            name='projectCompany',
        ),
        migrations.DeleteModel(
            name='accauntUser',
        ),
        migrations.DeleteModel(
            name='linkAddress',
        ),
        migrations.DeleteModel(
            name='projectName',
        ),
        migrations.AddField(
            model_name='link',
            name='urlProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_portfolio.Projects'),
        ),
    ]
