# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_portfolio', '0005_auto_20160612_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accauntuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
