# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_portfolio', '0007_auto_20160612_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accauntuser',
            old_name='email',
            new_name='email_address',
        ),
    ]
